(function() {
function g(a){throw a;}
var i=void 0,j=!0,k=null,m=!1,n=this,aa=function(a,b,c){a=a.split(".");c=c||n;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&b!==i?c[d]=b:c=c[d]?c[d]:c[d]={}},ba=function(a,b){for(var c=a.split("."),d=b||n,e;e=c.shift();)if(d[e]!=k)d=d[e];else return k;return d},ca=function(){},da=function(a){a.getInstance=function(){return a.Vf?a.Vf:a.Vf=new a}},ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof
Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},
fa=function(a){return"array"==ea(a)},ga=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length},o=function(a){return"string"==typeof a},ha=function(a){return"function"==ea(a)},ia=function(a){var b=typeof a;return"object"==b&&a!=k||"function"==b},la=function(a){return a[ja]||(a[ja]=++ka)},ja="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ka=0,ma=function(a,b,c){return a.call.apply(a.bind,arguments)},na=function(a,b,c){a||g(Error());if(2<arguments.length){var d=
Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},p=function(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ma:na;return p.apply(k,arguments)},oa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,
b)}},pa=Date.now||function(){return+new Date},qa=function(a,b,c){aa(a,b,c)},r=function(a,b,c){a[b]=c},s=function(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return p.apply(k,c)}return p(this,a)};Function.prototype.inherits=function(a){s(this,a)};var ra=function(a){Error.captureStackTrace?Error.captureStackTrace(this,ra):this.stack=Error().stack||"";a&&(this.message=String(a))};s(ra,Error);ra.prototype.name="CustomError";var sa=function(a,b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,d)}return a},ya=function(a,b){if(b)return a.replace(ta,"&amp;").replace(ua,"&lt;").replace(va,"&gt;").replace(wa,"&quot;");if(!xa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ta,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ua,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(va,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(wa,"&quot;"));return a},ta=/&/g,ua=/</g,va=/>/g,wa=/\"/g,xa=/[&<>\"]/,
za=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var l=d[h]||"",q=e[h]||"",t=RegExp("(\\d*)(\\D*)","g"),Y=RegExp("(\\d*)(\\D*)","g");do{var T=t.exec(l)||["","",""],M=Y.exec(q)||["","",""];if(0==T[0].length&&0==M[0].length)break;var c=0==T[1].length?0:parseInt(T[1],10),Mb=0==M[1].length?0:parseInt(M[1],10),c=(c<Mb?-1:c>Mb?1:0)||((0==T[2].length)<(0==M[2].length)?
-1:(0==T[2].length)>(0==M[2].length)?1:0)||(T[2]<M[2]?-1:T[2]>M[2]?1:0)}while(0==c)}return c};Math.random();var Aa=function(a,b){var c=o(b)?String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s",c=c?"|["+c+"]+":"",c=RegExp("(^"+c+")([a-z])","g");return a.replace(c,function(a,b,c){return b+c.toUpperCase()})};var Ba=function(a,b){b.unshift(a);ra.call(this,sa.apply(k,b));b.shift();this.messagePattern=a};s(Ba,ra);Ba.prototype.name="AssertionError";var Ca=function(a,b,c,d){var e="Assertion failed";if(c)var e=e+(": "+c),f=d;else a&&(e+=": "+a,f=b);g(new Ba(""+e,f||[]))},Da=function(a,b,c){a||Ca("",k,b,Array.prototype.slice.call(arguments,2));return a};var u=Array.prototype,Ea=u.indexOf?function(a,b,c){Da(a.length!=k);return u.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if(o(a))return!o(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Fa=u.forEach?function(a,b,c){Da(a.length!=k);u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=o(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ga=u.filter?function(a,b,c){Da(a.length!=k);return u.filter.call(a,b,c)}:function(a,
b,c){for(var d=a.length,e=[],f=0,h=o(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var q=h[l];b.call(c,q,l,a)&&(e[f++]=q)}return e},Ha=u.some?function(a,b,c){Da(a.length!=k);return u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=o(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return j;return m},Ia=function(a,b){return 0<=Ea(a,b)},Ka=function(a,b){var c=Ea(a,b),d;(d=0<=c)&&Ja(a,c);return d},Ja=function(a,b){Da(a.length!=k);return 1==u.splice.call(a,b,1).length},La=function(a){return u.concat.apply(u,
arguments)},Ma=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Na=Ma,Pa=function(a,b,c,d){Da(a.length!=k);return u.splice.apply(a,Oa(arguments,1))},Oa=function(a,b,c){Da(a.length!=k);return 2>=arguments.length?u.slice.call(a,b):u.slice.call(a,b,c)};var v=function(a,b){this.width=a;this.height=b};v.prototype.clone=function(){return new v(this.width,this.height)};v.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};v.prototype.area=function(){return this.width*this.height};v.prototype.Yc=function(){return this.width/this.height};v.prototype.Ya=function(){return!this.area()};v.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
v.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};v.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};v.prototype.scale=function(a,b){var c="number"==typeof b?b:a;this.width*=a;this.height*=c;return this};v.prototype.re=function(a){a=this.Yc()>a.Yc()?a.width/this.width:a.height/this.height;return this.scale(a)};var Qa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ra=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Sa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Ta=function(a){for(var b in a)return m;return j},Ua=function(a,b){var c;(c=b in a)&&delete a[b];return c},Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<
Va.length;f++)c=Va[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Xa=function(a){var b=arguments.length;if(1==b&&fa(arguments[0]))return Xa.apply(k,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=j;return c};var Ya,Za,$a,ab,bb,cb=function(){return n.navigator?n.navigator.userAgent:k},db=function(){return n.navigator},eb=function(){ab=$a=Za=Ya=m;var a;if(a=cb()){var b=db();Ya=0==a.indexOf("Opera");Za=!Ya&&-1!=a.indexOf("MSIE");($a=!Ya&&-1!=a.indexOf("WebKit"))&&a.indexOf("Mobile");ab=!Ya&&!$a&&"Gecko"==b.product}};eb();
var fb=Ya,w=Za,gb=ab,hb=$a,ib=function(){var a=db();return a&&a.platform||""},jb=ib(),kb=function(){bb=-1!=jb.indexOf("Mac");jb.indexOf("Win");jb.indexOf("Linux");db()&&(db().appVersion||"").indexOf("X11")};kb();
var lb=bb,nb=function(){var a="",b;fb&&n.opera?(a=n.opera.version,a="function"==typeof a?a():a):(gb?b=/rv\:([^\);]+)(\)|;)/:w?b=/MSIE\s+([^\);]+)(\)|;)/:hb&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(cb()))?a[1]:""));return w&&(b=mb(),b>parseFloat(a))?String(b):a},mb=function(){var a=n.document;return a?a.documentMode:i},ob=nb(),pb={},x=function(a){return pb[a]||(pb[a]=0<=za(ob,a))},qb=function(){var a=n.document;if(a&&w){var b=mb();return b||("CSS1Compat"==a.compatMode?parseInt(ob,10):5)}}();var rb,sb=!w||w&&9<=qb;!gb&&!w||w&&w&&9<=qb||gb&&x("1.9.1");w&&x("9");var tb=function(a){a=a.className;return o(a)&&a.match(/\S+/g)||[]},vb=function(a,b){var c=tb(a),d=Oa(arguments,1),e=c.length+d.length;ub(c,d);a.className=c.join(" ");return c.length==e},xb=function(a,b){var c=tb(a),d=Oa(arguments,1),e=wb(c,d);a.className=e.join(" ");return e.length==c.length-d.length},ub=function(a,b){for(var c=0;c<b.length;c++)Ia(a,b[c])||a.push(b[c])},wb=function(a,b){return Ga(a,function(a){return!Ia(b,a)})},yb=function(a,b,c){for(var d=tb(a),e=m,f=0;f<d.length;f++)d[f]==b&&(Pa(d,
f--,1),e=j);e&&(d.push(c),a.className=d.join(" "));return e};var Ab=function(a){return a?new y(zb(a)):rb||(rb=new y)},Bb=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return c=b+(c?"."+c:""),a.querySelectorAll(c);if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&Ia(b.split(/\s+/),c)&&(d[e++]=
h);d.length=e;return d}return a},Db=function(a,b){Qa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Cb?a.setAttribute(Cb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Cb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Fb=function(a,
b,c){return Eb(document,arguments)},Eb=function(a,b){var c=b[0],d=b[1];if(!sb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ya(d.name),'"');if(d.type){c.push(' type="',ya(d.type),'"');var e={};Wa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(o(d)?c.className=d:fa(d)?vb.apply(k,[c].concat(d)):Db(c,d));2<b.length&&Gb(a,c,b,2);return c},Gb=function(a,b,c,d){function e(c){c&&b.appendChild(o(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];ga(f)&&!(ia(f)&&
0<f.nodeType)?Fa(Hb(f)?Ma(f):f,e):e(f)}},Ib=Fb,Jb=function(a,b){a.appendChild(b)},Kb=function(a,b){Gb(zb(a),a,arguments,1)},Lb=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Nb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):k},Ob=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)},Pb=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=
b.parentNode;return b==a},zb=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Qb=function(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{Lb(a);var c=zb(a);a.appendChild(c.createTextNode(b))}},Hb=function(a){if(a&&"number"==typeof a.length){if(ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(ha(a))return"function"==typeof a.item}return m},y=
function(a){this.Ua=a||n.document||document};y.prototype.pc=function(){return this.Ua};y.prototype.C=function(a){return o(a)?this.Ua.getElementById(a):a};y.prototype.Cd=function(a,b,c){return Bb(this.Ua,a,b,c)};y.prototype.V=function(a,b,c){return Eb(this.Ua,arguments)};y.prototype.createElement=function(a){return this.Ua.createElement(a)};y.prototype.createTextNode=function(a){return this.Ua.createTextNode(a)};y.prototype.xd=function(){return this.Wf()?"CSS1Compat":"BackCompat"};
y.prototype.Wf=function(){return"CSS1Compat"==this.Ua.compatMode};y.prototype.appendChild=Jb;y.prototype.append=Kb;y.prototype.Vb=Lb;y.prototype.removeNode=Nb;y.prototype.replaceNode=Ob;y.prototype.contains=Pb;var Rb=function(){};Rb.prototype.md=m;Rb.prototype.dispose=function(){this.md||(this.md=j,this.G())};Rb.prototype.G=function(){this.Ch&&Sb.apply(k,this.Ch);if(this.og)for(;this.og.length;)this.og.shift()()};var Tb=function(a){a&&"function"==typeof a.dispose&&a.dispose()},Sb=function(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ga(d)?Sb.apply(k,d):Tb(d)}};var Ub=[],Vb=m,Wb=function(a){if(Vb)for(var b=Ub,c=0;c<b.length;c++)a(p(b[c].wrap,b[c]))};var Xb=function(a){Xb[" "](a);return a};Xb[" "]=ca;var Yb=function(a,b){try{return Xb(a[b]),j}catch(c){}return m};var Zb=!w||w&&9<=qb,$b=w&&!x("9");!hb||x("528");gb&&x("1.9b")||w&&x("8")||fb&&x("9.5")||hb&&x("528");gb&&!x("8")||w&&x("9");var z=function(a,b){this.type=a;this.currentTarget=this.target=b};z.prototype.G=function(){};z.prototype.dispose=function(){};z.prototype.Oa=m;z.prototype.ld=m;z.prototype.Xb=j;z.prototype.stopPropagation=function(){this.Oa=j};z.prototype.preventDefault=function(){this.ld=j;this.Xb=m};var A=function(a,b){a&&this.init(a,b)};s(A,z);A.prototype.target=k;A.prototype.relatedTarget=k;A.prototype.offsetX=0;A.prototype.offsetY=0;A.prototype.clientX=0;A.prototype.clientY=0;A.prototype.screenX=0;A.prototype.screenY=0;A.prototype.button=0;A.prototype.keyCode=0;A.prototype.charCode=0;A.prototype.ctrlKey=m;A.prototype.altKey=m;A.prototype.shiftKey=m;A.prototype.metaKey=m;A.prototype.Mg=m;A.prototype.lb=k;
A.prototype.init=function(a,b){var c=this.type=a.type;z.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?gb&&(Yb(d,"nodeName")||(d=k)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=hb||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=hb||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Mg=lb?a.metaKey:a.ctrlKey;this.state=a.state;this.lb=a;a.ld&&this.preventDefault();delete this.Oa};A.prototype.stopPropagation=function(){A.L.stopPropagation.call(this);this.lb.stopPropagation?this.lb.stopPropagation():this.lb.cancelBubble=j};
A.prototype.preventDefault=function(){A.L.preventDefault.call(this);var a=this.lb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=m,$b)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};A.prototype.G=function(){};var ac=function(){},bc=0;ac.prototype.key=0;ac.prototype.removed=m;ac.prototype.Db=m;ac.prototype.init=function(a,b,c,d,e,f){ha(a)?this.Yf=j:a&&a.za&&ha(a.za)?this.Yf=m:g(Error("Invalid listener argument"));this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.Db=m;this.key=++bc;this.removed=m};ac.prototype.za=function(a){return this.Yf?this.listener.call(this.handler||this.src,a):this.listener.za.call(this.listener,a)};var cc={},B={},dc={},ec="on",fc={},gc=function(a,b,c,d,e){if(fa(b)){for(var f=0;f<b.length;f++)gc(a,b[f],c,d,e);return k}return hc(a,b,c,m,d,e)},hc=function(a,b,c,d,e,f){b||g(Error("Invalid event type"));e=!!e;var h=B;b in h||(h[b]={l:0,fa:0});h=h[b];e in h||(h[e]={l:0,fa:0},h.l++);var h=h[e],l=la(a),q;h.fa++;if(h[l]){q=h[l];for(var t=0;t<q.length;t++)if(h=q[t],h.listener==c&&h.handler==f){if(h.removed)break;d||(q[t].Db=m);return q[t].key}}else q=h[l]=[],h.l++;t=ic();t.src=a;h=new ac;h.init(c,t,a,
b,e,f);h.Db=d;c=h.key;t.key=c;q.push(h);cc[c]=h;dc[l]||(dc[l]=[]);dc[l].push(h);a.addEventListener?(a==n||!a.kd)&&a.addEventListener(b,t,e):a.attachEvent(b in fc?fc[b]:fc[b]=ec+b,t);return c},ic=function(){var a=jc,b=Zb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b},kc=function(a,b,c,d,e){if(fa(b)){for(var f=0;f<b.length;f++)kc(a,b[f],c,d,e);return k}d=!!d;a=lc(a,b,d);if(!a)return m;for(f=0;f<a.length;f++)if(a[f].listener==c&&a[f].capture==
d&&a[f].handler==e)return mc(a[f].key);return m},mc=function(a){if(!cc[a])return m;var b=cc[a];if(b.removed)return m;var c=b.src,d=b.type,e=b.proxy,f=b.capture;c.removeEventListener?(c==n||!c.kd)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in fc?fc[d]:fc[d]=ec+d,e);c=la(c);dc[c]&&(e=dc[c],Ka(e,b),0==e.length&&delete dc[c]);b.removed=j;if(b=B[d][f][c])b.ig=j,nc(d,f,c,b);delete cc[a];return j},nc=function(a,b,c,d){if(!d.Cc&&d.ig){for(var e=0,f=0;e<d.length;e++)if(d[e].removed){var h=
d[e].proxy;h.src=k}else e!=f&&(d[f]=d[e]),f++;d.length=f;d.ig=m;0==f&&(delete B[a][b][c],B[a][b].l--,0==B[a][b].l&&(delete B[a][b],B[a].l--),0==B[a].l&&delete B[a])}},oc=function(a,b){var c=0,d=a==k,e=b==k;if(d)Qa(cc,function(a,b){mc(b);c++});else if(d=la(a),dc[d])for(var d=dc[d],f=d.length-1;0<=f;f--){var h=d[f];if(e||b==h.type)mc(h.key),c++}return c},lc=function(a,b,c){var d=B;return b in d&&(d=d[b],c in d&&(d=d[c],a=la(a),d[a]))?d[a]:k},pc=function(a,b,c,d,e){d=!!d;if(a=lc(a,b,d))for(b=0;b<a.length;b++)if(!a[b].removed&&
a[b].listener==c&&a[b].capture==d&&a[b].handler==e)return a[b];return k},rc=function(a,b,c,d,e){var f=1;b=la(b);if(a[b]){a.fa--;a=a[b];a.Cc?a.Cc++:a.Cc=1;try{for(var h=a.length,l=0;l<h;l++){var q=a[l];q&&!q.removed&&(f&=qc(q,e)!==m)}}finally{a.Cc--,nc(c,d,b,a)}}return Boolean(f)},qc=function(a,b){a.Db&&mc(a.key);return a.za(b)},sc=function(a,b){var c=b.type||b,d=B;if(!(c in d))return j;if(o(b))b=new z(b,a);else if(b instanceof z)b.target=b.target||a;else{var e=b;b=new z(c,a);Wa(b,e)}var e=1,f,d=d[c],
c=j in d,h;if(c){f=[];for(h=a;h;h=h.Fd())f.push(h);h=d[j];h.fa=h.l;for(var l=f.length-1;!b.Oa&&0<=l&&h.fa;l--)b.currentTarget=f[l],e&=rc(h,f[l],b.type,j,b)&&b.Xb!=m}if(h=m in d)if(h=d[m],h.fa=h.l,c)for(l=0;!b.Oa&&l<f.length&&h.fa;l++)b.currentTarget=f[l],e&=rc(h,f[l],b.type,m,b)&&b.Xb!=m;else for(d=a;!b.Oa&&d&&h.fa;d=d.Fd())b.currentTarget=d,e&=rc(h,d,b.type,m,b)&&b.Xb!=m;return Boolean(e)},jc=function(a,b){if(!cc[a])return j;var c=cc[a],d=c.type,e=B;if(!(d in e))return j;var e=e[d],f,h;if(!Zb){f=
b||ba("window.event");var l=j in e,q=m in e;if(l){if(0>f.keyCode||f.returnValue!=i)return j;tc(f)}var t=new A;t.init(f,this);f=j;try{if(l){for(var Y=[],T=t.currentTarget;T;T=T.parentNode)Y.push(T);h=e[j];h.fa=h.l;for(var M=Y.length-1;!t.Oa&&0<=M&&h.fa;M--)t.currentTarget=Y[M],f&=rc(h,Y[M],d,j,t);if(q){h=e[m];h.fa=h.l;for(M=0;!t.Oa&&M<Y.length&&h.fa;M++)t.currentTarget=Y[M],f&=rc(h,Y[M],d,m,t)}}else f=qc(c,t)}finally{Y&&(Y.length=0)}return f}d=new A(b,this);return f=qc(c,d)},tc=function(a){var b=m;
if(0==a.keyCode)try{a.keyCode=-1;return}catch(c){b=j}if(b||a.returnValue==i)a.returnValue=j};Wb(function(a){jc=a(jc)});var C=function(a){this.Va=a;this.J=[]};s(C,Rb);var uc=[];C.prototype.listen=function(a,b,c,d,e){fa(b)||(uc[0]=b,b=uc);for(var f=0;f<b.length;f++){var h=gc(a,b[f],c||this,d||m,e||this.Va||this);this.J.push(h)}return this};C.prototype.unlisten=function(a,b,c,d,e){if(fa(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else if(a=pc(a,b,c||this,d,e||this.Va||this))a=a.key,mc(a),Ka(this.J,a);return this};C.prototype.wb=function(){Fa(this.J,mc);this.J.length=0};
C.prototype.G=function(){C.L.G.call(this);this.wb()};C.prototype.za=function(){g(Error("EventHandler.handleEvent not implemented"))};var D=function(){};s(D,Rb);D.prototype.kd=j;D.prototype.Ic=k;D.prototype.Fd=function(){return this.Ic};D.prototype.$b=function(a){this.Ic=a};D.prototype.addEventListener=function(a,b,c,d){gc(this,a,b,c,d)};D.prototype.removeEventListener=function(a,b,c,d){kc(this,a,b,c,d)};D.prototype.dispatchEvent=function(a){return sc(this,a)};D.prototype.G=function(){D.L.G.call(this);oc(this);this.Ic=k};var E=function(a,b,c){o(b)?vc(a,c,b):Qa(b,oa(vc,a))},vc=function(a,b,c){(c=wc(a,c))&&(a.style[c]=b)},wc=function(a,b){var c=String(b).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()});if(a.style[c]===i){var d=(hb?"Webkit":gb?"Moz":w?"ms":fb?"O":k)+Aa(b);if(a.style[d]!==i)return d}return c},xc=function(a,b){var c=zb(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,k))?c[b]||c.getPropertyValue(b)||"":""},yc=function(a,b){return xc(a,b)||(a.currentStyle?
a.currentStyle[b]:k)||a.style&&a.style[b]},zc=function(a){var b=a.getBoundingClientRect();w&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b},Cc=function(a,b,c){b instanceof v?(c=b.height,b=b.width):c==i&&g(Error("missing height argument"));Ac(a,b);Bc(a,c)},Dc=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a},Bc=function(a,b){a.style.height=Dc(b,j)},Ac=function(a,b){a.style.width=Dc(b,j)},
Fc=function(a){if("none"!=yc(a,"display"))return Ec(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Ec(a);b.display=c;b.position=e;b.visibility=d;return a},Ec=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=hb&&!b&&!c;return(b===i||d)&&a.getBoundingClientRect?(a=zc(a),new v(a.right-a.left,a.bottom-a.top)):new v(b,c)},Gc=function(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=
""===b?"":"alpha(opacity="+100*b+")")},F=function(a,b){a.style.display=b?"":"none"},Ic=function(a,b){var c=Ab(b),d=k;if(w)d=c.pc().createStyleSheet(),Hc(d,a);else{var e=c.Cd("head")[0];e||(d=c.Cd("body")[0],e=c.V("head"),d.parentNode.insertBefore(e,d));d=c.V("style");Hc(d,a);c.appendChild(e,d)}return d},Hc=function(a,b){w?a.cssText=b:a.innerHTML=b};var Jc=function(){};da(Jc);Jc.prototype.jg=0;Jc.prototype.Ef=function(){return":"+(this.jg++).toString(36)};Jc.getInstance();var G=function(a){this.A=a||Ab();this.Pa=Kc};s(G,D);G.prototype.Pf=Jc.getInstance();var Kc=k;G.prototype.D=k;G.prototype.Wa=m;G.prototype.K=k;G.prototype.Pa=k;G.prototype.hg=k;G.prototype.ba=k;G.prototype.wa=k;G.prototype.gb=k;G.prototype.uh=m;G.prototype.Ed=function(){return this.D||(this.D=this.Pf.Ef())};G.prototype.C=function(){return this.K};
G.prototype.hh=function(a){this==a&&g(Error("Unable to set parent component"));a&&(this.ba&&this.D&&this.ba.wd(this.D)&&this.ba!=a)&&g(Error("Unable to set parent component"));this.ba=a;G.L.$b.call(this,a)};G.prototype.$b=function(a){this.ba&&this.ba!=a&&g(Error("Method not supported"));G.L.$b.call(this,a)};G.prototype.xc=function(){return this.Wa};G.prototype.V=function(){this.K=this.A.createElement("div")};G.prototype.render=function(a){this.Vg(a)};
G.prototype.Vg=function(a,b){this.Wa&&g(Error("Component already rendered"));this.K||this.V();a?a.insertBefore(this.K,b||k):this.A.pc().body.appendChild(this.K);(!this.ba||this.ba.xc())&&this.S()};G.prototype.Y=function(a){this.K=a};G.prototype.S=function(){this.Wa=j;this.kc(function(a){!a.xc()&&a.C()&&a.S()})};G.prototype.Z=function(){this.kc(function(a){a.xc()&&a.Z()});this.tc&&this.tc.wb();this.Wa=m};
G.prototype.G=function(){G.L.G.call(this);this.Wa&&this.Z();this.tc&&(this.tc.dispose(),delete this.tc);this.kc(function(a){a.dispose()});!this.uh&&this.K&&Nb(this.K);this.ba=this.hg=this.K=this.gb=this.wa=k};G.prototype.f=function(a){return this.Ed()+"."+a};G.prototype.zc=function(){this.Pa==k&&(this.Pa="rtl"==yc(this.Wa?this.K:this.A.pc().body,"direction"));return this.Pa};G.prototype.Mf=function(){return!!this.wa&&0!=this.wa.length};
G.prototype.wd=function(a){return this.gb&&a?(a in this.gb?this.gb[a]:i)||k:k};G.prototype.Bf=function(a){return this.wa?this.wa[a]||k:k};G.prototype.kc=function(a,b){this.wa&&Fa(this.wa,a,b)};G.prototype.removeChild=function(a,b){if(a){var c=o(a)?a:a.Ed();a=this.wd(c);c&&a&&(Ua(this.gb,c),Ka(this.wa,a),b&&(a.Z(),a.K&&Nb(a.K)),a.hh(k))}a||g(Error("Child is not in parent component"));return a};G.prototype.Ug=function(a,b){return this.removeChild(this.Bf(a),b)};
G.prototype.Vb=function(a){for(var b=[];this.Mf();)b.push(this.Ug(0,a));return b};var Lc="StopIteration"in n?n.StopIteration:Error("StopIteration"),Mc=function(){};Mc.prototype.next=function(){g(Lc)};Mc.prototype.__iterator__=function(){return this};var Nc=function(a){if("function"==typeof a.$)return a.$();if(o(a))return a.split("");if(ga(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ra(a)},Oc=function(a){if("function"==typeof a.Ka)return a.Ka();if("function"!=typeof a.$){if(ga(a)||o(a)){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return Sa(a)}},Pc=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ga(a)||o(a))Fa(a,b,c);else for(var d=Oc(a),e=Nc(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],
d&&d[h],a)};var H=function(a,b){this.la={};this.J=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.We(a)};H.prototype.l=0;H.prototype.Bb=0;H.prototype.oc=function(){return this.l};H.prototype.$=function(){this.hb();for(var a=[],b=0;b<this.J.length;b++){var c=this.J[b];a.push(this.la[c])}return a};H.prototype.Ka=function(){this.hb();return this.J.concat()};H.prototype.xa=function(a){return Qc(this.la,a)};
H.prototype.equals=function(a,b){if(this===a)return j;if(this.l!=a.oc())return m;var c=b||Rc;this.hb();for(var d,e=0;d=this.J[e];e++)if(!c(this.get(d),a.get(d)))return m;return j};var Rc=function(a,b){return a===b};H.prototype.Ya=function(){return 0==this.l};H.prototype.clear=function(){this.la={};this.Bb=this.l=this.J.length=0};H.prototype.remove=function(a){return Qc(this.la,a)?(delete this.la[a],this.l--,this.Bb++,this.J.length>2*this.l&&this.hb(),j):m};
H.prototype.hb=function(){if(this.l!=this.J.length){for(var a=0,b=0;a<this.J.length;){var c=this.J[a];Qc(this.la,c)&&(this.J[b++]=c);a++}this.J.length=b}if(this.l!=this.J.length){for(var d={},b=a=0;a<this.J.length;)c=this.J[a],Qc(d,c)||(this.J[b++]=c,d[c]=1),a++;this.J.length=b}};H.prototype.get=function(a,b){return Qc(this.la,a)?this.la[a]:b};H.prototype.set=function(a,b){Qc(this.la,a)||(this.l++,this.J.push(a),this.Bb++);this.la[a]=b};
H.prototype.We=function(a){var b;a instanceof H?(b=a.Ka(),a=a.$()):(b=Sa(a),a=Ra(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};H.prototype.clone=function(){return new H(this)};H.prototype.__iterator__=function(a){this.hb();var b=0,c=this.J,d=this.la,e=this.Bb,f=this,h=new Mc;h.next=function(){for(;;){e!=f.Bb&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(Lc);var h=c[b++];return a?h:d[h]}};return h};
var Qc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Sc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Uc=function(a){Tc();return a.match(Sc)},Vc=hb,Tc=function(){if(Vc){Vc=m;var a=n.location;if(a){var b=a.href;if(b&&(b=Wc(Uc(b)[3]||k))&&b!=a.hostname)Vc=j,g(Error())}}},Wc=function(a){return a&&decodeURIComponent(a)};var I=function(a,b){var c;a instanceof I?(this.aa=b!==i?b:a.Df(),this.Ee(a.Kd()),this.Je(a.Ld()),this.xe(a.Bd()),this.Ce(a.Hd()),this.Be(a.Gd()),this.De(a.rc().clone()),this.ye(a.Dd())):a&&(c=Uc(String(a)))?(this.aa=!!b,this.Ee(c[1]||"",j),this.Je(c[2]||"",j),this.xe(c[3]||"",j),this.Ce(c[4]),this.Be(c[5]||"",j),this.De(c[6]||"",j),this.ye(c[7]||"",j)):(this.aa=!!b,this.sa=new J(k,k,this.aa))},Xc=m;I.prototype.yb="";I.prototype.Te="";I.prototype.hc="";I.prototype.Kc=k;I.prototype.le="";
I.prototype.ud="";I.prototype.Zf=m;I.prototype.aa=m;I.prototype.toString=function(){var a=[],b=this.Kd();b&&a.push(Yc(b,Zc),":");if(b=this.Bd()){a.push("//");var c=this.Ld();c&&a.push(Yc(c,Zc),"@");a.push(encodeURIComponent(String(b)));b=this.Hd();b!=k&&a.push(":",String(b))}if(b=this.Gd())this.Nf()&&"/"!=b.charAt(0)&&a.push("/"),a.push(Yc(b,"/"==b.charAt(0)?$c:ad));(b=this.Cf())&&a.push("?",b);(b=this.Dd())&&a.push("#",Yc(b,bd));return a.join("")};I.prototype.clone=function(){return new I(this)};
I.prototype.Kd=function(){return this.yb};I.prototype.Ee=function(a,b){this.ha();if(this.yb=b?a?decodeURIComponent(a):"":a)this.yb=this.yb.replace(/:$/,"");return this};I.prototype.Ld=function(){return this.Te};I.prototype.Je=function(a,b){this.ha();this.Te=b?a?decodeURIComponent(a):"":a;return this};I.prototype.Bd=function(){return this.hc};I.prototype.xe=function(a,b){this.ha();this.hc=b?a?decodeURIComponent(a):"":a;return this};I.prototype.Nf=function(){return!!this.hc};I.prototype.Hd=function(){return this.Kc};
I.prototype.Ce=function(a){this.ha();a?(a=Number(a),(isNaN(a)||0>a)&&g(Error("Bad port number "+a)),this.Kc=a):this.Kc=k;return this};I.prototype.Gd=function(){return this.le};I.prototype.Be=function(a,b){this.ha();this.le=b?a?decodeURIComponent(a):"":a;return this};I.prototype.De=function(a,b){this.ha();a instanceof J?(this.sa=a,this.sa.Zb(this.aa)):(b||(a=Yc(a,cd)),this.sa=new J(a,k,this.aa));return this};I.prototype.Cf=function(){return this.sa.toString()};I.prototype.rc=function(){return this.sa};
I.prototype.o=function(a,b){this.ha();this.sa.set(a,b);return this};I.prototype.Ae=function(a,b){this.ha();fa(b)||(b=[String(b)]);this.sa.Ke(a,b);return this};I.prototype.Dd=function(){return this.ud};I.prototype.ye=function(a,b){this.ha();this.ud=b?a?decodeURIComponent(a):"":a;return this};I.prototype.removeParameter=function(a){this.ha();this.sa.remove(a);return this};I.prototype.ha=function(){this.Zf&&g(Error("Tried to modify a read-only Uri"))};
I.prototype.Zb=function(a){this.aa=a;this.sa&&this.sa.Zb(a);return this};I.prototype.Df=function(){return this.aa};var Yc=function(a,b){return o(a)?encodeURI(a).replace(b,dd):k},dd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Zc=/[#\/\?@]/g,ad=/[\#\?:]/g,$c=/[\#\?]/g,cd=/[\#\?@]/g,bd=/#/g,J=function(a,b,c){this.Ia=a||k;this.aa=!!c};
J.prototype.oa=function(){if(!this.I&&(this.I=new H,this.l=0,this.Ia))for(var a=this.Ia.split("&"),b=0;b<a.length;b++){var c=a[b].indexOf("="),d=k,e=k;0<=c?(d=a[b].substring(0,c),e=a[b].substring(c+1)):d=a[b];d=decodeURIComponent(d.replace(/\+/g," "));d=this.Ja(d);this.add(d,e?decodeURIComponent(e.replace(/\+/g," ")):"")}};J.prototype.I=k;J.prototype.l=k;J.prototype.oc=function(){this.oa();return this.l};
J.prototype.add=function(a,b){this.oa();this.Xa();a=this.Ja(a);var c=this.I.get(a);c||this.I.set(a,c=[]);c.push(b);this.l++;return this};J.prototype.remove=function(a){this.oa();a=this.Ja(a);return this.I.xa(a)?(this.Xa(),this.l-=this.I.get(a).length,this.I.remove(a)):m};J.prototype.clear=function(){this.Xa();this.I=k;this.l=0};J.prototype.Ya=function(){this.oa();return 0==this.l};J.prototype.xa=function(a){this.oa();a=this.Ja(a);return this.I.xa(a)};
J.prototype.Ka=function(){this.oa();for(var a=this.I.$(),b=this.I.Ka(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};J.prototype.$=function(a){this.oa();var b=[];if(a)this.xa(a)&&(b=La(b,this.I.get(this.Ja(a))));else{a=this.I.$();for(var c=0;c<a.length;c++)b=La(b,a[c])}return b};J.prototype.set=function(a,b){this.oa();this.Xa();a=this.Ja(a);this.xa(a)&&(this.l-=this.I.get(a).length);this.I.set(a,[b]);this.l++;return this};
J.prototype.get=function(a,b){var c=a?this.$(a):[];return Xc?0<c.length?c[0]:b:0<c.length?String(c[0]):b};J.prototype.Ke=function(a,b){this.remove(a);0<b.length&&(this.Xa(),this.I.set(this.Ja(a),Na(b)),this.l+=b.length)};
J.prototype.toString=function(){if(this.Ia)return this.Ia;if(!this.I)return"";for(var a=[],b=this.I.Ka(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.$(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.Ia=a.join("&")};J.prototype.Xa=function(){this.Ia=k};J.prototype.clone=function(){var a=new J;a.Ia=this.Ia;this.I&&(a.I=this.I.clone(),a.l=this.l);return a};
J.prototype.Ja=function(a){a=String(a);this.aa&&(a=a.toLowerCase());return a};J.prototype.Zb=function(a){var b=a&&!this.aa;b&&(this.oa(),this.Xa(),Pc(this.I,function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.Ke(e,a))},this));this.aa=a};J.prototype.extend=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];Pc(c,function(a,b){this.add(b,a)},this)}};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var K=function(a,b){this.Pc=[];this.Xh=a;this.Ah=b||k};K.prototype.rd=m;K.prototype.ob=m;K.prototype.fc=m;K.prototype.$c=m;K.prototype.Le=m;K.prototype.ff=0;K.prototype.hd=function(a,b){this.fc=m;this.Vc(a,b)};K.prototype.Vc=function(a,b){this.rd=j;this.qe=b;this.ob=!a;this.qd()};K.prototype.cd=function(){this.vc()&&(this.Le||g(new ed(this)),this.Le=m)};K.prototype.callback=function(a){this.cd();this.Zc(a);this.Vc(j,a)};K.prototype.errback=function(a){this.cd();this.Zc(a);this.Vc(m,a)};
K.prototype.Zc=function(a){Da(!(a instanceof K),"An execution sequence may not be initiated with a blocking Deferred.")};K.prototype.Xe=function(a,b){return this.Xc(k,a,b)};K.prototype.Xc=function(a,b,c){Da(!this.$c,"Blocking Deferreds can not be re-used");this.Pc.push([a,b,c]);this.vc()&&this.qd();return this};K.prototype.vc=function(){return this.rd};K.prototype.Xf=function(a){return a instanceof Error};K.prototype.Rd=function(){return Ha(this.Pc,function(a){return ha(a[1])})};
K.prototype.qd=function(){this.Qe&&(this.vc()&&this.Rd())&&(n.clearTimeout(this.Qe),delete this.Qe);this.ba&&(this.ba.ff--,delete this.ba);for(var a=this.qe,b=m,c=m;this.Pc.length&&!this.fc;){var d=this.Pc.shift(),e=d[0],f=d[1],d=d[2];if(e=this.ob?f:e)try{var h=e.call(d||this.Ah,a);h!==i&&(this.ob=this.ob&&(h==a||this.Xf(h)),this.qe=a=h);a instanceof K&&(this.fc=c=j)}catch(l){a=l,this.ob=j,this.Rd()||(b=j)}}this.qe=a;c&&(a.Xc(p(this.hd,this,j),p(this.hd,this,m)),a.$c=j);b&&(this.Qe=n.setTimeout(function(){g(a)},
0))};var ed=function(a){ra.call(this);this.deferred=a};s(ed,ra);ed.prototype.message="Deferred has already fired";ed.prototype.name="AlreadyCalledError";var jd=function(a,b){var c=b||{},d=c.document||document,e=document.createElement("SCRIPT"),f={Yg:e,ec:i},h=new K(fd,f),l=k,q=c.timeout!=k?c.timeout:5E3;0<q&&(l=window.setTimeout(function(){gd(e,j);h.errback(new hd(1,"Timeout reached for loading script "+a))},q),f.ec=l);e.onload=e.onreadystatechange=function(){if(!e.readyState||"loaded"==e.readyState||"complete"==e.readyState){var a=c.cleanupWhenDone||m;gd(e,a,l);h.callback(k)}};e.onerror=function(){gd(e,j,l);h.errback(new hd(0,"Error while loading script "+
a))};Db(e,{type:"text/javascript",charset:"UTF-8",src:a});d=id(d);d.appendChild(e);return h},id=function(a){var b=a.getElementsByTagName("HEAD");return!b||0==b.length?a.documentElement:b[0]},fd=function(){var a=this;if(a&&a.Yg){var b=a.Yg;b&&"SCRIPT"==b.tagName&&gd(b,j,a.ec)}},gd=function(a,b,c){c!=k&&n.clearTimeout(c);a.onload=ca;a.onerror=ca;a.onreadystatechange=ca;b&&window.setTimeout(function(){Nb(a)},0)},hd=function(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);ra.call(this,c);this.code=
a};s(hd,ra);var kd=function(a,b){this.Q=new I(a);this.xh=b?b:"callback";this.ec=5E3},ld=0;kd.prototype.ac=function(a){this.ec=a};kd.prototype.send=function(a,b,c,d){a=a||k;d=d||"_"+(ld++).toString(36)+pa().toString(36);n._callbacks_||(n._callbacks_={});var e=this.Q.clone();a&&md(a,e);b&&(b=nd(d,b),n._callbacks_[d]=b,e.Ae(this.xh,"_callbacks_."+d));b=jd(e.toString(),{timeout:this.ec,cleanupWhenDone:j});c=od(d,a,c);b.Xe(c);return{D:d,Uh:b}};
var od=function(a,b,c){return function(){pd(a,m);c&&c(b)}},nd=function(a,b){return function(c){pd(a,j);b.apply(i,arguments)}},pd=function(a,b){n._callbacks_[a]&&(b?delete n._callbacks_[a]:n._callbacks_[a]=ca)},md=function(a,b){for(var c in a)(!a.hasOwnProperty||a.hasOwnProperty(c))&&b.Ae(c,a[c]);return b};var qd=function(a,b){b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};var rd=n,sd=function(a,b,c){ha(a)?c&&(a=p(a,c)):a&&"function"==typeof a.za?a=p(a.za,a):g(Error("Invalid listener argument"));return 2147483647<b?-1:rd.setTimeout(a,b||0)},td=function(a){rd.clearTimeout(a)};var ud=function(a,b,c){this.Qb=a;this.Dh=b||0;this.Va=c;this.Eb=p(this.Kb,this)};s(ud,Rb);ud.prototype.D=0;ud.prototype.G=function(){ud.L.G.call(this);this.stop();delete this.Qb;delete this.Va};ud.prototype.start=function(a){this.stop();this.D=sd(this.Eb,a!==i?a:this.Dh)};ud.prototype.stop=function(){this.pb()&&td(this.D);this.D=0};ud.prototype.pb=function(){return 0!=this.D};ud.prototype.Kb=function(){this.D=0;this.Qb&&this.Qb.call(this.Va)};var L=function(a,b,c){this.Qb=a;this.Va=c;this.va=b||window;this.Eb=p(this.Kb,this)};s(L,Rb);L.prototype.D=k;L.prototype.Wc=m;L.prototype.start=function(){this.stop();this.Wc=m;var a=this.Jd(),b=this.vd();a&&!b&&this.va.mozRequestAnimationFrame?(this.D=gc(this.va,"MozBeforePaint",this.Eb),this.va.mozRequestAnimationFrame(k),this.Wc=j):this.D=a&&b?a.call(this.va,this.Eb):this.va.setTimeout(qd(this.Eb),20)};
L.prototype.stop=function(){if(this.pb()){var a=this.Jd(),b=this.vd();a&&!b&&this.va.mozRequestAnimationFrame?mc(this.D):a&&b?b.call(this.va,this.D):this.va.clearTimeout(this.D)}this.D=k};L.prototype.pb=function(){return this.D!=k};L.prototype.Kb=function(){this.Wc&&this.D&&mc(this.D);this.D=k;this.Qb.call(this.Va,pa())};L.prototype.G=function(){this.stop();L.L.G.call(this)};
L.prototype.Jd=function(){var a=this.va;return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||k};L.prototype.vd=function(){var a=this.va;return a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||k};var vd={},wd=k,xd=k,zd=function(a){var b=la(a);b in vd||(vd[b]=a);yd()},Bd=function(a){a=la(a);delete vd[a];Ta(vd)&&Ad()},yd=function(){xd||(xd=wd?new L(function(a){Cd(a)},wd):new ud(function(){Cd(pa())},20));var a=xd;a.pb()||a.start()},Ad=function(){xd&&xd.stop()},Cd=function(a){Qa(vd,function(b){b.kg(a)});Ta(vd)||yd()};var N=function(){this.Ea=0;this.endTime=this.startTime=k};s(N,D);var Dd={STOPPED:0,PAUSED:-1,PLAYING:1};N.prototype.Hf=function(){return this.Ea};N.prototype.nh=function(){this.Ea=1};N.prototype.mh=function(){this.Ea=-1};N.prototype.He=function(){this.Ea=0};N.prototype.yc=function(){return 1==this.Ea};N.prototype.Vd=function(){return-1==this.Ea};N.prototype.Wd=function(){return 0==this.Ea};N.prototype.Ub=function(){this.ca("begin")};N.prototype.ub=function(){this.ca("end")};N.prototype.pg=function(){this.ca("finish")};
N.prototype.vg=function(){this.ca("pause")};N.prototype.wg=function(){this.ca("play")};N.prototype.zg=function(){this.ca("resume")};N.prototype.Cg=function(){this.ca("stop")};N.prototype.ca=function(a){this.dispatchEvent(a)};var O=function(a,b,c,d){N.call(this);(!fa(a)||!fa(b))&&g(Error("Start and end parameters must be arrays"));a.length!=b.length&&g(Error("Start and end points must be the same length"));this.startPoint=a;this.endPoint=b;this.duration=c;this.Ue=d;this.coords=[];this.Qh=m};s(O,N);O.prototype.$f=function(){return this.Qh};var Ed=Dd;O.prototype.td=0;O.prototype.progress=0;O.prototype.Ac=k;
O.prototype.play=function(a){if(a||this.Wd())this.progress=0,this.coords=this.startPoint;else if(this.yc())return m;Bd(this);this.startTime=a=pa();this.Vd()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Ac=this.startTime;this.progress||this.Ub();this.wg();this.Vd()&&this.zg();this.nh();zd(this);this.cycle(a);return j};O.prototype.stop=function(a){Bd(this);this.He();a&&(this.progress=1);this.Re(this.progress);this.Cg();this.ub()};
O.prototype.pause=function(){this.yc()&&(Bd(this),this.mh(),this.vg())};O.prototype.Gf=function(){return this.progress};O.prototype.G=function(){this.Wd()||this.stop(m);this.ng();O.L.G.call(this)};O.prototype.kg=function(a){this.cycle(a)};O.prototype.cycle=function(a){this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<=this.progress&&(this.progress=1);this.td=1E3/(a-this.Ac);this.Ac=a;this.Re(this.progress);1==this.progress?(this.He(),Bd(this),this.pg(),this.ub()):this.yc()&&this.Tb()};
O.prototype.Re=function(a){ha(this.Ue)&&(a=this.Ue(a));this.coords=Array(this.startPoint.length);for(var b=0;b<this.startPoint.length;b++)this.coords[b]=(this.endPoint[b]-this.startPoint[b])*a+this.startPoint[b]};O.prototype.Tb=function(){this.ca("animate")};O.prototype.ng=function(){this.ca("destroy")};O.prototype.ca=function(a){this.dispatchEvent(new Fd(a,this))};
var Fd=function(a,b){z.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.Gf();this.fps=b.td;this.state=b.Hf();this.anim=b};s(Fd,z);var P=function(a,b,c,d,e){O.call(this,b,c,d,e);this.element=a};s(P,O);P.prototype.Sa=ca;P.prototype.zc=function(){this.Pa===i&&(this.Pa="rtl"==yc(this.element,"direction"));return this.Pa};P.prototype.Tb=function(){this.Sa();P.L.Tb.call(this)};P.prototype.ub=function(){this.Sa();P.L.ub.call(this)};P.prototype.Ub=function(){this.Sa();P.L.Ub.call(this)};var Gd=function(a,b,c,d,e){(2!=b.length||2!=c.length)&&g(Error("Start and end points must be 2D"));P.apply(this,arguments)};s(Gd,P);
Gd.prototype.Sa=function(){var a=this.$f()&&this.zc()?"right":"left";this.element.style[a]=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var Hd=function(a,b,c,d,e){"number"==typeof b&&(b=[b]);"number"==typeof c&&(c=[c]);P.call(this,a,b,c,d,e);(1!=b.length||1!=c.length)&&g(Error("Start and end points must be 1D"))};s(Hd,P);Hd.prototype.Sa=function(){Gc(this.element,this.coords[0])};Hd.prototype.show=function(){this.element.style.display=""};
Hd.prototype.hide=function(){this.element.style.display="none"};Math.pow(1024,-3);Math.pow(1024,-2);Math.pow(1024,2);Math.pow(1024,3);Math.pow(1024,4);Math.pow(1024,5);w&&x(8);var Id=function(a,b){a!=k&&this.append.apply(this,arguments)};Id.prototype.Fa="";Id.prototype.set=function(a){this.Fa=""+a};Id.prototype.append=function(a,b,c){this.Fa+=a;if(b!=k)for(var d=1;d<arguments.length;d++)this.Fa+=arguments[d];return this};Id.prototype.clear=function(){this.Fa=""};Id.prototype.toString=function(){return this.Fa};var Q=Id;

var pe=function(a,b){var c=b||new Q;c.append('<div id="',a.rootId,'" style="overflow: hidden; width: 100%; height: 100%; position: relative">');a.pauseImage&&me(a.pauseImage,c);a.controlPanel?ne(a.controlPanel,c):a.customControlPanel&&oe(a.customControlPanel,c);c.append("</div>");if(!b)return c.toString()},me=function(a,b){var c=b||new Q;c.append('<div id="',a.id,'" style="position: absolute; visibility: hidden; z-index: 222">&nbsp;</div>');if(!b)return c.toString()},ne=function(a,b){var c=b||new Q;
c.append('<div style="background-color: #000000; height: ',a.height,"; width: 100%; bottom: 0; left: 0; position: absolute; z-index: 222; direction: ltr; padding: ",a.paddingTop," 0 ",a.paddingBottom,' 0; text-align: center;" id="',a.id,'"><img id="',a.prevId,'" src="',a.prevSrc,'" style="cursor: ',a.cursorStyle,'"/><img id="',a.pauseId,'" src="',a.pauseSrc,'" style="cursor: ',a.cursorStyle,'; margin: 0 5px"/><img id="',a.nextId,'" src="',a.nextSrc,'" style="cursor: ',a.cursorStyle,'"/>',a.cursor?
'<div id="'+a.cursor.id+'" style="height: 1.3em; font-size: 11px; color: #bbbbbb"/>':"","</div>");if(!b)return c.toString()},oe=function(a,b){var c=b||new Q;c.append('<div class="ss-control" id="',a.id,'"><div class="ss-control-bg"></div><table class="ss-control-table"><tr><td class="ss-control-prev-cell"><div id="',a.prevId,'" class="ss-control-prev"></div></td><td class="ss-control-pause-cell"><div id="',a.pauseId,'" class="ss-control-pause"></div></td><td class="ss-control-next-cell"><div id="',
a.nextId,'" class="ss-control-next"></div></td></tr></table></div>');if(!b)return c.toString()};function V(a,b,c,d){G.call(this,d);this.g=new C(this);this.jb=this.Lb=k;"string"==typeof a?this.Lb=a:"object"==typeof a&&"number"==typeof a.length?this.jb=a:g("invalid argument: photoFeed");"string"==typeof b&&(b=this.A.C(b));this.O=b;this.ma(c);this.Lb?(this.pd=new google.feeds.Feed(this.Lb),this.pd.setResultFormat(google.feeds.Feed.MIXED_FORMAT),this.pd.setNumEntries(this.a.numResults),this.pd.load(p(this.od,this))):this.jb&&this.od(this.jb)}V.inherits(G);
V.prototype.V=function(){var a=this.A.createElement("div");E(a,"width","100%");E(a,"height","100%");this.Y(a)};
V.prototype.Y=function(a){this.K=a;a={rootId:this.f("root")};this.a.pauseOnHover&&(a.pauseImage={id:this.f("pauseImage")});if(this.a.fullControlPanel){var b,c,d,e=5;this.a.fullControlPanelSmallIcons?(c=25,d=5,b="small"):(c=45,d=10,b="big");this.a.fullControlPanelCursor&&(c+=10);a.controlPanel={id:this.f("controlPanel"),height:c+"px",paddingTop:d+"px",paddingBottom:e+"px",prevId:this.f("controlPrev"),prevSrc:qe[b],pauseId:this.f("controlPause"),pauseSrc:re[b],nextId:this.f("controlNext"),nextSrc:se[b],
cursorStyle:w?"hand":"pointer"};this.a.fullControlPanelCursor&&(a.controlPanel.cursor={id:this.f("cursor")})}else this.a.customControlPanel&&(a.customControlPanel={id:this.f("controlPanel"),prevId:this.f("controlPrev"),pauseId:this.f("controlPause"),nextId:this.f("controlNext")});this.K.innerHTML=pe(a)};
V.prototype.S=function(){V.L.S.call(this);this.M=this.A.C(this.f("root"));this.Ca=Fc(this.M);if(this.a.fullControlPanel||this.a.customControlPanel)this.d=new te,this.d.container=this.A.C(this.f("controlPanel")),this.d.pauseButton=this.A.C(this.f("controlPause")),this.d.prevButton=this.A.C(this.f("controlPrev")),this.d.nextButton=this.A.C(this.f("controlNext")),F(this.d.container,m),this.g.listen(this.d.prevButton,"click",this.Mb),this.g.listen(this.d.pauseButton,"click",this.Ig),this.g.listen(this.d.nextButton,
"click",this.Nb),this.a.fullControlPanel?(this.d.defaultOpacity=0.65,this.d.playCallback=this.a.fullControlPanelPlayCallback,this.d.fadeOutTime=this.a.fullControlPanelFadeOutTime):(this.d.defaultOpacity=1,this.d.playCallback=this.a.customControlPanelPlayCallback,this.d.fadeOutTime=this.a.customControlPanelFadeOutTime,w?(this.d.classSuffix="-ie",this.d.prevButton.className+=this.d.classSuffix,this.d.pauseButton.className+=this.d.classSuffix,this.d.nextButton.className+=this.d.classSuffix):this.d.classSuffix=
"");if(this.a.pauseOnHover){this.H=this.A.C(this.f("pauseImage"));var a=this.A.createElement("img");a.setAttribute("src",this.a.pauseImage);this.H.appendChild(a);a.complete?this.Qd({currentTarget:a}):this.g.listen(a,"load",this.Qd)}};V.prototype.Qd=function(a){a=a.currentTarget;if(this.a.scalePauseImage){var b=Fc(a);b.re(this.Ca.clone().scale(0.33));Cc(a,b)}this.mf(a);this.Lg()};
V.prototype.mf=function(a){Cc(this.H,Fc(a));E(this.H,"position","absolute");w?(this.H.style.filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+a.src+'", sizingMethod="scale")',this.H.removeChild(a)):E(this.H,"opacity","")};
V.prototype.Lg=function(){var a=Fc(this.H),b=this.Ca.height-a.height,a=this.Ca.width-a.width;E(this.H,"top","0");E(this.H,"left","0");if(0<b){var c=Math.round(0.1*this.Ca.height);15>c&&(c=10);b-=c;0>b&&(b=0);E(this.H,"top",this.H.offsetTop+b+this.a.pauseCenterBias.topBias+"px")}0<a&&(b=Math.round(a/2),E(this.H,"left",this.H.offsetLeft+b+this.a.pauseCenterBias.leftBias+"px"))};
V.prototype.ma=function(a){var b;b="undefined"!=typeof google&&google.feeds!=i?google.feeds.Feed.MAX_ENTRIES:20;this.a={numResults:b,scaleImages:m,thumbnailTag:"thumbnail",thumbnailNamespace:"http://search.yahoo.com/mrss/",thumbnailSize:"large",linkTarget:k,clickableImage:m,displayTime:3E3,transitionTime:1E3,transitionStep:40,pauseOnHover:j,pauseImage:ue,pauseStateCallback:k,scalePauseImage:j,autoCleanup:j,thumbnailUrlResolver:k,transitionCallback:k,transitionAnimationCallback:k,feedLoadCallback:k,
feedProcessedCallback:k,imageClickCallback:k,centerBias:{topBias:0,leftBias:0},pauseCenterBias:{topBias:0,leftBias:0},fullControlPanel:m,fullControlPanelCursor:m,fullControlPanelFadeOutTime:5E3,fullControlPanelPlayCallback:k,fullControlPanelSmallIcons:m,maintainAspectRatio:j,customControlPanel:m,customControlPanelFadeOutTime:5E3,customControlPanelPlayCallback:k};if(a)for(var c in this.a)"undefined"!=typeof a[c]&&(this.a[c]=a[c]);100>this.a.displayTime&&(this.a.displayTime=100);a=this.a.transitionTime/
this.a.transitionStep;this.Bh=Math.min(1,1/a);this.Me=m};V.prototype.uc=function(a){for(a=a.relatedTarget;a!=k;){if(a==this.M)return;a=a.parentNode}this.d?(this.a.pauseOnHover&&!this.W&&this.Jc(),this.nd()):(this.W=j,this.H&&E(this.H,"visibility","visible"));this.a.pauseStateCallback&&this.a.pauseStateCallback(this.W)};
V.prototype.Ob=function(a){for(a=a.relatedTarget;a!=k;){if(a==this.M)return;a=a.parentNode}this.d?(this.ic(),this.g.unlisten(this.M,"mousemove",this.Ob),this.a.pauseOnHover&&this.W&&this.Jc()):(this.W=m,this.H&&E(this.H,"visibility","hidden"));this.a.pauseStateCallback&&this.a.pauseStateCallback(this.W);this.Ha==k&&this.cb==k&&this.Jb()};V.prototype.Fg=function(){var a=this.ya[this.N],a=this.jd(a.link);a.click()};
V.prototype.pause=function(a){if(!this.W){var b=this.H;a&&(this.H=k);this.me();this.H=b;this.a.fullControlPanel?(a=this.a.fullControlPanelSmallIcons?"small":"big",this.d.pauseButton.src=ve[a]):this.a.customControlPanel&&(this.d.pauseButton.className="ss-control-play"+this.d.classSuffix)}};
V.prototype.resume=function(){if(this.W)if(this.Wb(),this.a.fullControlPanel){var a=this.a.fullControlPanelSmallIcons?"small":"big";this.d.pauseButton.src=re[a]}else this.a.customControlPanel&&(this.d.pauseButton.className="ss-control-pause"+this.d.classSuffix)};V.prototype.me=function(){this.W=j;this.H&&E(this.H,"visibility","visible");this.g.unlisten(this.M,"mouseout",this.Pd);this.a.imageClickCallback&&this.a.imageClickCallback(this.ya[this.N])};
V.prototype.Wb=function(){if(this.a.pauseOnHover||this.d)this.g.listen(this.M,"mouseover",this.uc),this.g.listen(this.M,"mouseout",this.Ob);this.W=m;this.H&&E(this.H,"visibility","hidden");this.Ha==k&&this.cb==k&&this.Jb()};V.prototype.If=function(a){var b=0;1<a.length&&("large"==this.a.thumbnailSize?b=a.length-1:"medium"==this.a.thumbnailSize&&(b=Math.floor(a.length/2)));a=a[b];b=a.getAttribute("url");b||(b=a.firstChild.nodeValue);return b};
V.prototype.pe=function(a,b){this.Uc=k;var c=this.rh,d=this.ya.length,e=a||4;if(d>c+e){var d=c+e,e=p(this.pe,this),f=b||Math.round(this.a.displayTime/4);this.Uc=window.setTimeout(e,f)}for(;c<d;c++)e=this.ya[c].thumbUrl,e=this.qf(e),this.T.push(e),this.a.linkTarget||this.a.clickableImage?fb?(this.g.listen(e,"click",this.Fg),E(e,"cursor","pointer"),this.M.appendChild(e)):(f=this.jd(this.ya[c].link),f.appendChild(e),this.M.appendChild(f)):this.M.appendChild(e),e.complete?this.Od({currentTarget:e}):(this.g.listen(e,
"load",this.Od),this.g.listen(e,"error",this.Jf)),this.rh++};V.prototype.Og=function(a){for(var b=0;b<a.length;b++){var c=k;if(this.a.thumbnailUrlResolver)c=this.a.thumbnailUrlResolver(a[b]);else{var d=google.feeds.getElementsByTagNameNS(a[b].xmlNode,this.a.thumbnailNamespace,this.a.thumbnailTag);d&&0<d.length&&(c=this.If(d))}c&&(a[b].thumbUrl=c,this.ya.push(a[b]))}};
V.prototype.od=function(a){this.a.feedLoadCallback&&this.a.feedLoadCallback(a);if(this.Lb&&a.error||this.jb&&0==this.jb.length)this.a.feedLoadCallback||(this.O.innerHTML="<center>feed could not be loaded.</center>");else{this.A.Vb(this.O);this.render(this.O);this.T=[];this.ya=[];this.rh=0;var b;b=this.Lb?a.feed.entries:this.jb;this.Og(b);this.a.feedProcessedCallback&&this.a.feedProcessedCallback(a);if((this.a.pauseOnHover||this.d)&&0<this.ya.length)this.g.listen(this.M,"mouseover",this.uc),this.g.listen(this.M,
"mouseout",this.Ob);this.a.imageClickCallback&&this.g.listen(this.M,"click",this.me);this.pe(1,100+100*Math.random())}};V.prototype.Od=function(a){a=a.currentTarget;a.__gfloaded=j;this.Ye(a);if(!this.Me)for(var b=0;b<this.T.length;){a==this.T[b]&&this.$e(b);break}};V.prototype.Jf=function(a){a=a.currentTarget;a.__gferror=j};V.prototype.Ye=function(a){this.a.scaleImages&&(this.a.maintainAspectRatio?this.Xg(a):Cc(a,this.Ca));this.gf(a)};
V.prototype.Xg=function(a,b,c){var d=Fc(a);0>=d.width||0>=d.height||(b=new v(b||this.Ca.width,c||this.Ca.height),d.re(b),Cc(a,d))};V.prototype.gf=function(a){var b=this.Ca.height-a.offsetHeight,c=this.Ca.width-a.offsetWidth;E(a,"top","0px");E(a,"left","0px");0<b&&(b=Math.round(b/2),E(a,"top",a.offsetTop+b+this.a.centerBias.topBias+"px"));0<c&&(c=Math.round(c/2),E(a,"left",a.offsetLeft+c+this.a.centerBias.leftBias+"px"))};
V.prototype.jd=function(a){var b=this.A.createElement("a");b.setAttribute("href",a);this.a.linkTarget&&b.setAttribute("target",this.a.linkTarget);return b};V.prototype.qf=function(a){var b=this.A.createElement("img");E(b,"position","absolute");b.setAttribute("src",a);we(b,0);return b};V.prototype.Hb=function(){this.cb&&(window.clearInterval(this.cb),this.cb=k)};V.prototype.oh=function(){this.Hb();this.cg=xe();var a=p(this.sh,this);this.cb=window.setInterval(a,this.a.transitionStep)};
V.prototype.jf=function(){this.Ha&&(window.clearTimeout(this.Ha),this.Ha=k)};V.prototype.we=function(){if(!this.Ha){var a=p(this.Jb,this);this.Ha=window.setTimeout(a,this.a.displayTime)}};V.prototype.kf=function(){this.Uc&&(window.clearTimeout(this.Uc),this.Uc=k)};V.prototype.$e=function(a){this.N=a;this.X=this.T[this.N];this.$a("transition-startup");this.Me=j};var xe=function(){var a=new Date;return a.getTime()};V.prototype.Nb=function(){this.jc();this.ze();this.$a("transition-go-forward");this.Gb()};
V.prototype.Mb=function(){this.jc();this.kh();this.$a("transition-go-backward");this.Gb()};V.prototype.Md=function(a){a!=this.N&&(this.cb&&(we(this.X,0),this.Hb()),this.jh(a),this.$a("transition-go-index"),this.Gb())};V.prototype.Ig=function(){this.d&&this.d.playCallback&&this.W?(this.gd(),this.d.playCallback(this.ya[this.N]),this.ic()):this.Jc()};
V.prototype.Jc=function(){if(this.W){this.W=m;if(this.a.fullControlPanel){var a=this.a.fullControlPanelSmallIcons?"small":"big";this.d.pauseButton.src=re[a]}else this.a.customControlPanel&&(this.d.pauseButton.className="ss-control-pause"+this.d.classSuffix);this.Ha==k&&this.cb==k&&this.Jb()}else this.W=j,this.a.fullControlPanel?(a=this.a.fullControlPanelSmallIcons?"small":"big",this.d.pauseButton.src=ve[a]):this.a.customControlPanel&&(this.d.pauseButton.className="ss-control-play"+this.d.classSuffix)};
V.prototype.Pd=function(){var a=this.d.container.opacity;a<this.d.defaultOpacity?(this.g.unlisten(this.M,"mousemove",this.Pd),this.Gb(),this.nd()):this.eh()};V.prototype.Gb=function(){this.d&&this.d.timeout&&(window.clearTimeout(this.d.timeout),this.d.timeout=k)};V.prototype.eh=function(){this.d.timeout&&(window.clearTimeout(this.d.timeout),this.d.timeout=k);if(0<this.d.fadeOutTime){var a=p(this.ic,this);this.d.timeout=window.setTimeout(a,this.d.fadeOutTime)}};
V.prototype.nd=function(){this.d.animation&&this.d.animation.stop();this.d.animation=new ye(this.d.container,0,this.d.defaultOpacity,300);this.d.animation.play()};V.prototype.ic=function(){this.d.animation&&this.d.animation.stop();this.d.animation=new ze(this.d.container,this.d.defaultOpacity,0,300);this.d.animation.play()};
V.prototype.sh=function(){if(this.Ta&&this.X){var a=this.Bh,b=this.a.transitionStep,c=xe(),d=c-this.cg;this.cg=c;a*=d/b;if(0>a)return;b=this.Ta.opacity-a;a=this.X.opacity+a;we(this.Ta,b);we(this.X,a);this.a.transitionAnimationCallback&&this.a.transitionAnimationCallback(this.X.opacity);if(0<b)return}this.jc()};
V.prototype.ze=function(){if(0!=this.T.length)for(var a=this.N,b=m;!b;){++this.N>=this.T.length&&(this.N=0);var c=this.T[this.N];c&&c.__gfloaded?(this.X=c,b=j):this.N==a&&(this.X=this.T[0],b=j)}};V.prototype.kh=function(){for(var a=this.N,b=m;!b&&0!=this.T.length;){0>--this.N&&(this.N=this.T.length-1);var c=this.T[this.N];c&&c.__gfloaded?(this.X=c,b=j):this.N==a&&(this.X=this.T[0],b=j)}};V.prototype.jh=function(a){if(!(0>a||a>=this.T.length)){var b=this.T[a];b&&b.__gfloaded&&(this.X=b,this.N=a)}};
V.prototype.gd=function(){this.g.unlisten(this.M,"mouseover",this.uc);this.g.unlisten(this.M,"mouseout",this.Ob)};V.prototype.dispose=function(){this.Hb();this.jf();this.kf();this.gd();this.g.dispose();this.A.Vb(this.O);this.O=k};V.prototype.Jb=function(){this.Ha=k;if(!this.Me)return m;this.W||((!this.M||!this.M.parentNode)&&this.a.autoCleanup?this.dispose():(this.ze(),this.af()))};
V.prototype.$a=function(a){we(this.X,1);this.Ta!=this.X&&(we(this.Ta,0),this.Ta=this.X);this.we();this.a.transitionCallback&&this.a.transitionCallback(this.ya[this.N],this.a.transitionTime,a);this.a.fullControlPanel&&this.a.fullControlPanelCursor&&(a=this.N+1+" / "+this.T.length,this.d.cursor.innerHTML=a)};V.prototype.af=function(){!this.Ta||!this.X||this.Ta==this.next?this.we():this.a.transitionTime>=this.a.transitionStep?this.oh():this.$a("transition-timer")};
V.prototype.jc=function(){this.Hb();this.$a("transition-timer")};var te=function(){this.timeout=this.pauseImage=this.container=k};function we(a,b){a!=k&&(b=Math.max(0,Math.min(1,b)),0==b?E(a,"visibility","hidden"):E(a,"visibility","visible"),a.opacity=b,Gc(a,b))}function ze(a,b,c,d,e){Hd.call(this,a,b,c,d,e);gc(this,"begin",this.show,m,this);gc(this,"end",this.hide,m,this)}s(ze,Hd);ze.prototype.stop=function(){this.Ea!=Ed.STOPPED&&ze.L.stop.call(this)};
function ye(a,b,c,d,e){Hd.call(this,a,b,c,d,e);gc(this,"begin",this.show,m,this)}s(ye,Hd);ye.prototype.stop=function(){this.Ea!=Ed.STOPPED&&ye.L.stop.call(this)};
var ue=google.loader.ServiceBase+"/solutions/slideshow/pause.png",Ae=google.loader.ServiceBase+"/solutions/slideshow/play.png",re={small:google.loader.ServiceBase+"/solutions/slideshow/btn_pause_small.png",big:google.loader.ServiceBase+"/solutions/slideshow/btn_pause.png"},ve={small:google.loader.ServiceBase+"/solutions/slideshow/btn_play_small.png",big:google.loader.ServiceBase+"/solutions/slideshow/btn_play.png"},qe={small:google.loader.ServiceBase+"/solutions/slideshow/btn_prev_small.png",big:google.loader.ServiceBase+
"/solutions/slideshow/btn_prev.png"},se={small:google.loader.ServiceBase+"/solutions/slideshow/btn_next_small.png",big:google.loader.ServiceBase+"/solutions/slideshow/btn_next.png"};qa("google.elements.SlideShow",V);r(V,"THUMBNAILS_SMALL","small");r(V,"THUMBNAILS_MEDIUM","medium");r(V,"THUMBNAILS_LARGE","large");r(V,"MRSS_THUMBNAIL_TAG","thumbnail");r(V,"MRSS_THUMBNAIL_NS","http://search.yahoo.com/mrss/");r(V,"ITMS_THUMBNAIL_TAG","coverArt");r(V,"ITMS_THUMBNAIL_NS","http://phobos.apple.com/rss/1.0/modules/itms/");
r(V,"DEFAULT_THUMBNAIL_TAG","thumbnail");r(V,"DEFAULT_THUMBNAIL_NS","http://search.yahoo.com/mrss/");r(V,"DEFAULT_DISPLAY_TIME",3E3);r(V,"DEFAULT_TRANSISTION_TIME",1E3);r(V,"DEFAULT_TRANSISTION_STEP",40);r(V,"DEFAULT_PAUSE_PNG",ue);r(V,"DEFAULT_PLAY_PNG",Ae);r(V,"TRANSITION_TIMER","transition-timer");r(V,"TRANSITION_STARTUP","transition-startup");r(V,"TRANSITION_GO_BACKWARD","transition-go-backward");r(V,"TRANSITION_GO_FORWARD","transition-go-forward");r(V,"TRANSITION_GO_INDEX","transition-go-index");
r(V.prototype,"pause",V.prototype.pause);r(V.prototype,"resume",V.prototype.resume);r(V.prototype,"goForward",V.prototype.Nb);r(V.prototype,"goBackward",V.prototype.Mb);r(V.prototype,"gotoIndex",V.prototype.Md);

var _UDS_CONST_LOCALE = 'en';
var _UDS_CONST_SHORT_DATE_PATTERN = 'MDY'; 
var _UDS_MSG_SEARCHER_NEWS = ('News'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' minutes ago');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 hour ago'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' hours ago');} 
var _UDS_MSG_NEWS_RELATED = ('Related Articles'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('Jan'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('Feb'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('Mar'); 
var _UDS_MSG_MONTH_ABBR_APR = ('Apr'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('May'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('Jun'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('Jul'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('Aug'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('Sep'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('Oct'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('Nov'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('Dec'); 
var _UDS_MSG_POWERED_BY = ('powered by'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Previous'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Next'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Ads by Google'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('Top Stories'); 
var _UDS_MSG_NEWSCAT_WORLD = ('World'); 
var _UDS_MSG_NEWSCAT_NATION = ('Nation'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('Business'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('Sci/Tech'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('Entertainment'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('Health'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('Sports'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('Politics');
var Le=function(a,b){var c=b||new Q;c.append('<div id="',a.rootId,'" class="',a.activeClass,'"><div class="gns-basecanvas"><div class="gns-poweredby"><a class="gns-poweredby-link" target="',a.linkTarget,'" href="',a.poweredbylink,'"/><img class="gns-clearimg" src="',a.clearUrl,'"/></a></div><div class="gns-ss-frame"><div id="',a.ssId,'" class="gns-ss-image gns-pausable"></div></div><div id="',a.ssTitleId,'" class="gns-ss-title gns-pausable"></div><div id="',a.resultId,'" class="gns-result gns-pausable"></div><div id="',
a.adId,'" style="display:none;" class="gns-ads gns-pausable"></div>',a.sponsor!=k&&a.sponsor.link!=i?'<div class="gns-sponsor"><a class="gns-sponsor-text-link" target="'+a.linkTarget+'" href="'+a.sponsor.link+'"><img class="gns-clearimg" src="'+a.clearUrl+'"/></a></div>':"",'<div id="',a.qTitleId,'" class="gns-query-title"></div></div></div>');if(!b)return c.toString()},Me=function(a,b){var c=b||new Q;c.append('<div id="',a.rootId,'" class="',a.activeClass,'"><div class="gns-basecanvas"><div class="gns-poweredby"><a class="gns-poweredby-link" target="',
a.linkTarget,'" href="',a.poweredbylink,'"/><img class="gns-clearimg" src="',a.clearUrl,'"/></a></div><div class="gns-ssdivider"></div><div class="gns-clusterdivider"></div><div class="gns-ss-frame"><div id="',a.ssId,'" class="gns-ss-image gns-pausable"></div></div><div id="',a.ssTitleId,'" class="gns-ss-title gns-pausable"></div><div id="',a.resultId,'" class="gns-result gns-pausable"></div><div id="',a.adId,'" style="display:none;" class="gns-ads gns-pausable"></div><div id="',a.clusterId,'" class="gns-clusterresults gns-pausable"></div><div id="',
a.cursorId,'" class="gns-cursorcontrols gns-pausable"></div>',a.sponsor!=k&&a.sponsor.link!=i?'<div class="gns-sponsor"><a class="gns-sponsor-text-link" target="'+a.linkTarget+'" href="'+a.sponsor.link+'"><img class="gns-clearimg" src="'+a.clearUrl+'"/></a></div>':"",'<div id="',a.qTitleId,'" class="gns-query-title"></div></div></div>');if(!b)return c.toString()},Ne=function(a,b){var c=b||new Q;c.append('<div class="gns-title gns-linktrackable" id="',a.La,'"><a class="gns-title-link" target="',a.R,
'" href="',a.unescapedUrl,'">',a.titleNoFormatting,'</a></div><div class="gns-sourceandtime"><span class="gns-source">',a.publisher,'</span><span class="gns-date"> - ',a.Tg,'</span></div><div class="gns-snippet">',a.content,"</div>",a.clusterUrl!=i?'<div class="gns-cluster"><a class="gns-cluster-link" target="'+a.R+'" href="'+a.clusterUrl+'">'+a.db.MSG_NEWS_RELATED+'&nbsp;&raquo;</a><div class="gns-cursor-wrapper '+a.ta+'"><span class="gns-cursor" id="down">&laquo;&nbsp;'+a.db.MSG_SEARCHCONTROL_PREVIOUS+
'</span><span class="gns-cursor-space">&nbsp;</span><span class="gns-cursor" id="up">'+a.db.MSG_SEARCHCONTROL_NEXT+"&nbsp;&raquo;</span></div></div>":"");if(!b)return c.toString()},Oe=function(a,b){var c=b||new Q;c.append('<div class="gns-title gns-linktrackable" id="',a.La,'"><a class="gns-title-link" target="',a.R,'" href="',a.unescapedUrl,'">',a.titleNoFormatting,'</a></div><div class="gns-sourceandtime"><span class="gns-source">',a.publisher,'</span><span class="gns-date"> - ',a.Tg,'</span></div><div class="gns-snippet">',
a.content,"</div>");if(!b)return c.toString()},Pe=function(a,b){var c=b||new Q;if(a.clusterUrl!=i&&a.relatedStories!=i&&0<a.relatedStories.length){for(var d=0;2>d;d+=1)c.append(d<a.relatedStories.length?'<div class="gns-title gns-linktrackable" id="'+a.relatedStories[d].La+'"><a class="gns-title-link" target="'+a.R+'" href="'+a.relatedStories[d].unescapedUrl+'">'+a.relatedStories[d].titleNoFormatting+"</a></div>":"");if(2<a.relatedStories.length){c.append('<div class="gns-cluster-publishers">');for(var d=
a.relatedStories.length,e=0;e<d;e+=1)c.append(1<e?'<span class="gns-publisher gns-linktrackable" id="'+a.relatedStories[e].La+'"><a class="gns-publisher-link" target="'+a.R+'" href="'+a.relatedStories[e].unescapedUrl+'">'+a.relatedStories[e].publisher+"</a></span>"+(e+1<a.relatedStories.length?'<span class="gns-publisher-spacer"> - </span>':""):"");c.append("</div>")}c.append('<div class="gns-cluster"><a class="gns-cluster-link" target="',a.R,'" href="',a.clusterUrl,'">',a.db.MSG_NEWS_RELATED,"&nbsp;&raquo;</a></div>")}if(!b)return c.toString()},
Qe=function(a,b){var c=b||new Q;c.append('<div class="gns-cursor-wrapper ',a.ta,'"><span class="gns-cursor" id="down">&laquo;&nbsp;',a.db.MSG_SEARCHCONTROL_PREVIOUS,'</span><span class="gns-cursor-space">&nbsp;</span><span class="gns-cursor" id="up">',a.db.MSG_SEARCHCONTROL_NEXT,"&nbsp;&raquo;</span></div>");if(!b)return c.toString()},Re=function(a,b){var c=b||new Q;c.append('<div class="gns-sstitle"><a class="gns-sstitle-link" target="',a.R,'" href="',a.image.originalContextUrl,'">',a.image.publisher,
"</a></div>");if(!b)return c.toString()},Se=function(a,b){var c=b||new Q;c.append('<div class="gns-qtitle">',a.Sg,"</div>");if(!b)return c.toString()},Te=function(a,b){var c=b||new Q;c.append('<div style="position:relative;width:100%;height:100%;overflow:hidden;"><a class="gns-bootimage-link" target="',a.linkTarget,'" href="',a.link,'"><img style="position:absolute;top:',a.topPos,";left:",a.leftPos,';" src="',a.tbUrl,'"/></a></div>');if(!b)return c.toString()};function X(a,b,c){G.call(this,c);this.g=new C(this);"string"==typeof a&&(a=this.A.C(a));this.O=a;this.ta=m;this.wh=k;this.c={};this.Sc={};this.Za=[];this.ga=[];this.cc=k;this.ih=j;w&&6>=ob&&(this.ih=m);this.ma(b);0<this.Za.length&&(this.pf(),this.render(this.O),this.Za[0].ae(p(this.df,this)))}X.inherits(G);X.prototype.V=function(){this.Y(this.A.createElement("div"))};X.prototype.Y=function(a){this.K=a;this.K.innerHTML=this.vh(this.Sc.boot)};
X.prototype.S=function(){X.L.S.call(this);var a=[];a.push("_base");a.push(this.a.format);for(var b=0;b<a.length;b++){var c=a[b],d;for(d in Ue[c].keyNodes){var e=Ue[c].keyNodes[d];this.c[d]=this.A.C(this.f(e))}}this.ia()};X.prototype.Z=function(){X.L.Z.call(this);this.g.wb()};
var Ue={_base:{keyNodes:{root:"rootId",ss:"ssId",ssTitle:"ssTitleId",qTitle:"qTitleId",ad:"adId"}},"728x90":{keyNodes:{result:"resultId"},bootTemplate:Le},"300x250":{keyNodes:{result:"resultId",cluster:"clusterId",cursor:"cursorId"},bootTemplate:Me}};
X.prototype.pf=function(){var a={},b=[];b.push("_base");b.push(this.a.format);for(var c=0;c<b.length;c++){var d=b[c],e;for(e in Ue[d].keyNodes){var f=Ue[d].keyNodes[e];a[f]=this.f(f)}}a.sponsor=this.a.sponsor;a.linkTarget=this.a.linkTarget;a.clearUrl=this.zh;a.poweredby=Z.MSG_POWERED_BY;a.poweredbylink=this.a.element?"http://www.google.com/webelements":"http://news.google.com";b=w&&6>=ob?".gif":".png";a.poweredbylogo=google.loader.ServiceBase+"/css/small-logo"+b;a.activeClass=this.Cb;a.pausedClass=
this.Jg;this.Sc.boot=a};
X.prototype.ma=function(a){this.a={format:"728x90",linkTarget:"_parent",brandingLink:"http://news.google.com",deferResumeTime:300,deferBootTime:2500,displayTime:7500,transitionTime:400,sponsor:k,enableAds:k,publisherId:"pub-3122923178966709",pageUrl:k,hl:k,queryList:Ve,element:m};if(a)for(var b in this.a)"undefined"!=typeof a[b]&&(this.a[b]=a[b]);"728x90"!=this.a.format&&"300x250"!=this.a.format&&(this.a.format="728x90");this.vh=Ue[this.a.format].bootTemplate;this.lh();this.zh=google.loader.ServiceBase+
"/modules/elements/newsshow/cleardot.gif";this.Pg()};X.prototype.lh=function(){var a="generic";this.a.sponsor!=i?a="branded":this.a.element&&(a="element");var b="gns-root gns-"+this.a.format+" gns-"+a+"-"+this.a.format;this.Jg=b+" gns-paused-"+this.a.format+" gns-"+a+"-paused-"+this.a.format;this.Cb=b+" gns-active-"+this.a.format+" gns-"+a+"-active-"+this.a.format};X.prototype.Pg=function(){for(var a=0;a<this.a.queryList.length;a++){var b=this.a.queryList[a],b=new We(a,b,this);this.Za.push(b)}};
X.prototype.df=function(a){if(a.Bc){var b=a.i[0];b.La=this.f("resultIndexId-0");b.nb=0;if(b.relatedStories&&0<b.relatedStories.length)for(var c=0;c<b.relatedStories.length;c++){var d=b.relatedStories[c];d.La=this.f("relatedStoryId-")+b.nb+";"+c}this.ga.push(b);this.of(b);this.Hc(b,k,google.elements.SlideShow.TRANSITION_STARTUP);this.a.enableAds&&a.na&&a.eg();for(b=0;b<this.Za.length;b++)a=this.Za[b],!a.Bc&&0!=b&&a.ae(k);this.wh=window.setTimeout(p(this.ef,this),this.a.deferBootTime)}};
X.prototype.Qc=function(a){this.ih&&("paused"==a?this.c.root.className=this.Jg:"active"==a&&(this.c.root.className=this.Cb))};X.prototype.of=function(a){var b={topPos:0,leftPos:0},c=82-a.image.tbWidth,d=62-a.image.tbHeight;0<d&&(b.topPos=Math.round(d/2));0<c&&(b.leftPos=Math.round(c/2));b.topPos+="px";b.leftPos+="px";b.linkTarget=this.a.linkTarget;b.link=a.unescapedUrl;b.tbUrl=a.image.tbUrl;a=Te(b);this.c.ss.innerHTML=a};
X.prototype.ef=function(){this.ga=[];for(var a=0,b=0;b<this.Za.length;b++){var c=this.Za[b];if(c.Bc){for(var d=0;d<c.i.length;d++){var e=c.i[d];e.nb=a++;e.La=this.f("resultIndexId-")+e.nb;if(e.relatedStories&&0<e.relatedStories.length)for(var f=0;f<e.relatedStories.length;f++){var h=e.relatedStories[f];h.La=this.f("relatedStoryId-")+e.nb+";"+f}this.ga.push(e)}c.eb&&(c.eb.nb=a++,c.eb.La=this.f("adIndexId-")+c.eb.nb,this.ga.push(c.eb))}}0<this.ga.length&&(this.Qc("active"),this.cc=new google.elements.SlideShow(this.ga,
this.c.ss,this.Ib()),this.ta=j,this.Hc(this.ga[0],k,google.elements.SlideShow.TRANSITION_STARTUP))};X.prototype.Ib=function(){var a={};a.linkTarget=this.a.linkTarget;a.displayTime=this.a.displayTime;a.transitionTime=this.a.transitionTime;a.scaleImages=m;a.pauseOnHover=m;a.fullControlPanel=m;a.transitionCallback=p(this.Hc,this);a.thumbnailUrlResolver=p(this.dc,this);return a};X.prototype.dc=function(a){return a.image.tbUrl};
X.prototype.Hc=function(a){this.c.qTitle.innerHTML=Se(a);"GnewsSearch"==a.GsearchResultClass?(a.ta=this.ta?"gns-ready":"gns-notready",this.c.ssTitle.innerHTML=Re(a),this.c.ad.style.display="none","728x90"==this.a.format?this.c.result.innerHTML=Ne(a):"300x250"==this.a.format&&(this.c.result.innerHTML=Oe(a),this.c.cluster.innerHTML=Pe(a),this.c.cursor.innerHTML=Qe(a))):(a.ta=this.ta?"gns-ready":"gns-notready",this.c.ad.style.display="block")};
X.prototype.ia=function(){this.g.listen(this.c.result,"mousedown",p(this.Fc,this));this.g.listen(this.c.result,"mouseover",p(this.ra,this));this.g.listen(this.c.result,"mouseout",p(this.qa,this));this.g.listen(this.c.ad,"mouseover",p(this.ra,this));this.g.listen(this.c.ad,"mouseout",p(this.qa,this));this.g.listen(this.c.ss,"mouseover",p(this.ra,this));this.g.listen(this.c.ss,"mouseout",p(this.qa,this));this.g.listen(this.c.ssTitle,"mouseover",p(this.ra,this));this.g.listen(this.c.ssTitle,"mouseout",
p(this.qa,this));"300x250"==this.a.format&&(this.g.listen(this.c.cluster,"mousedown",p(this.Fc,this)),this.g.listen(this.c.cursor,"mouseover",p(this.ra,this)),this.g.listen(this.c.cursor,"mouseout",p(this.qa,this)),this.g.listen(this.c.cluster,"mouseover",p(this.ra,this)),this.g.listen(this.c.cluster,"mouseout",p(this.qa,this)),this.g.listen(this.c.cursor,"mousedown",p(this.Fc,this)))};
X.prototype.Fc=function(a){if(this.ta)for(var b=a.target;b!=k;){var c=b.className;if(c&&0<=c.indexOf("gns-linktrackable")){var d=b.id,b=k;0<=d.indexOf("resultIndexId")?(d=d.substring(d.lastIndexOf("-")+1),this.ga[d]!=i&&(d=this.ga[d],d.signedRedirectUrl&&(b=d.signedRedirectUrl))):0<=d.indexOf("relatedStoryId")&&(c=d.substring(d.lastIndexOf(";")+1),d=d.substring(d.lastIndexOf("-")+1,d.lastIndexOf(";")),this.ga[d]!=i&&(d=this.ga[d],d.relatedStories&&c<d.relatedStories.length&&(c=d.relatedStories[c],
c.signedRedirectUrl&&(b=c.signedRedirectUrl))));if(b)switch(a.type){case "mousedown":a=b+"&nocache="+Number(new Date),b=new Image,b.src=a}break}else c&&0<=c.indexOf("gns-cursor")&&(d=b.id,"down"==d?this.cc.Mb():"up"==d&&this.cc.Nb());b=b.parentNode}};X.prototype.ra=function(a){if(this.ta)for(a=a.target;a!=k;){var b=a.className;if(b&&0<=b.indexOf("gns-pausable")){this.xb&&(window.clearTimeout(this.xb),this.xb=k);this.Qc("paused");this.cc.pause(j);this.Ne="paused";break}a=a.parentNode}};
X.prototype.qa=function(a){if(this.ta)for(a=a.target;a!=k;){var b=a.className;if(b&&0<=b.indexOf("gns-pausable")){this.Wb();break}a=a.parentNode}};X.prototype.Wb=function(){this.xb&&(window.clearTimeout(this.xb),this.xb=k);"paused"==this.Ne&&(this.Ne="resumed",this.xb=window.setTimeout(p(this.Wg,this),this.a.deferResumeTime))};X.prototype.Wg=function(){this.Ne="resumed";this.Qc("active");this.cc.resume()};
function We(a,b,c){this.D=a;this.Gc=k;this.Bc=m;this.i=[];this.eb=k;this.na="";this.R=c.a.linkTarget;this.mc=c.a.format;this.Vh=c.a.enableAds;this.Sd=c.a.hl;this.c=c.c;this.Jh=c.a.publisherId;this.Gg=c.a.pageUrl;this.Na=new Xe("search/news");this.Na.o("source","uds-ns-"+this.mc);var d=c=a=m,e=m,f;for(f in b)switch(f){case "rsz":a=j;this.Na.o(f,b[f]);break;case "topic":d=j;this.Na.o(f,b[f]);break;case "q":e=j;this.Na.o(f,b[f]);break;case "ned":case "geo":case "scoring":this.Na.o(f,b[f]);break;case "title":c=
j,this.na=b[f]}a||this.Na.o("rsz","large");this.Sd!=i&&this.Na.o("hl",this.Sd);c||(d?(b=b.topic,Ye[b]!=i&&(this.na=Ye[b])):e&&(b=decodeURIComponent(b.q),this.na=ya(b).replace(/\s*[(]?site:.*/,"")))}We.prototype.ae=function(a){a&&(this.Gc=a);this.Na.send(k,p(this.fg,this))};
We.prototype.eg=function(){var a={GsearchResultClass:"GnewsSearch.ad",Kh:this};a.Sg=this.na;var b={format:this.mc,color_border:"ccd9f2",color_link:"000099",color_url:"008000",language:this.Sd};this.Gg?(b.page_url=this.Gg,b.hints=this.na):b.keywords=this.na;a.Sh=new google.ads.Ad(this.Jh,this.c.ad,b);a.image={};a.image.url=google.loader.ServiceBase+"/modules/elements/newsshow/no-image-80x60.gif";a.image.tbUrl=a.image.url;a.image.originalContextUrl="http://news.google.com";a.image.publisher=Z.MSG_ADS_BY_GOOGLE;
a.image.tbWidth="80";a.image.tbHeight="60";this.eb=a};
We.prototype.fg=function(a){if(200==a.responseStatus&&a.responseData.results&&0<a.responseData.results.length){this.i=a.responseData.results;for(a=0;a<this.i.length;a++){this.i[a].Kh=this;this.i[a].Sg=this.na;if(this.i[a].signedRedirectUrl){this.i[a].ke=this.i[a].signedRedirectUrl;var b=new I(this.i[a].ke);b.o("fd","AS");b.o("client","uds-ns-"+this.mc);this.i[a].signedRedirectUrl=b.toString()}if(this.i[a].relatedStories&&0<this.i[a].relatedStories.length)for(var c=0;c<this.i[a].relatedStories.length;c++){var d=
this.i[a].relatedStories[c];d.signedRedirectUrl&&(d.ke=d.signedRedirectUrl,b=new I(d.ke),b.o("fd","AS"),b.o("client","uds-ns-"+this.mc),d.signedRedirectUrl=b.toString())}this.i[a].R=this.R;this.i[a].link=this.i[a].unescapedUrl;this.i[a].db=Z;this.i[a].Tg=Ze(new Date(this.i[a].publishedDate),Z);this.i[a].image==i&&(this.i[a].image={},this.i[a].image.url=google.loader.ServiceBase+"/modules/elements/newsshow/no-image-80x60.gif",this.i[a].image.tbUrl=this.i[a].image.url,this.i[a].image.originalContextUrl=
"http://news.google.com",this.i[a].image.publisher="",this.i[a].image.tbWidth="80",this.i[a].image.tbHeight="60")}this.Bc=j}this.Gc&&(a=this.Gc,this.Gc=k,a(this))};
var Z={MSG_MINUTES_AGO:_UDS_MSG_MINUTES_AGO,MSG_ONE_HOUR_AGO:_UDS_MSG_ONE_HOUR_AGO,MSG_HOURS_AGO:_UDS_MSG_HOURS_AGO,MSG_NEWS_RELATED:_UDS_MSG_NEWS_RELATED,MSG_POWERED_BY:_UDS_MSG_POWERED_BY,MSG_SEARCHCONTROL_PREVIOUS:_UDS_MSG_SEARCHCONTROL_PREVIOUS,MSG_SEARCHCONTROL_NEXT:_UDS_MSG_SEARCHCONTROL_NEXT,MSG_MONTH_ABBR:[_UDS_MSG_MONTH_ABBR_JAN,_UDS_MSG_MONTH_ABBR_FEB,_UDS_MSG_MONTH_ABBR_MAR,_UDS_MSG_MONTH_ABBR_APR,_UDS_MSG_MONTH_ABBR_MAY,_UDS_MSG_MONTH_ABBR_JUN,_UDS_MSG_MONTH_ABBR_JUL,_UDS_MSG_MONTH_ABBR_AUG,
_UDS_MSG_MONTH_ABBR_SEP,_UDS_MSG_MONTH_ABBR_OCT,_UDS_MSG_MONTH_ABBR_NOV,_UDS_MSG_MONTH_ABBR_DEC],CONST_LOCALE:_UDS_CONST_LOCALE,CONST_SHORT_DATE_PATTERN:_UDS_CONST_SHORT_DATE_PATTERN,MSG_ADS_BY_GOOGLE:_UDS_MSG_ADS_BY_GOOGLE,MSG_SEARCHER_NEWS:_UDS_MSG_SEARCHER_NEWS,MSG_NEWSCAT_TOPSTORIES:_UDS_MSG_NEWSCAT_TOPSTORIES,MSG_NEWSCAT_WORLD:_UDS_MSG_NEWSCAT_WORLD,MSG_NEWSCAT_NATION:_UDS_MSG_NEWSCAT_NATION,MSG_NEWSCAT_BUSINESS:_UDS_MSG_NEWSCAT_BUSINESS,MSG_NEWSCAT_SCITECH:_UDS_MSG_NEWSCAT_SCITECH,MSG_NEWSCAT_ENTERTAINMENT:_UDS_MSG_NEWSCAT_ENTERTAINMENT,
MSG_NEWSCAT_HEALTH:_UDS_MSG_NEWSCAT_HEALTH,MSG_NEWSCAT_SPORTS:_UDS_MSG_NEWSCAT_SPORTS,MSG_NEWSCAT_POLITICS:_UDS_MSG_NEWSCAT_POLITICS},cf=function(a){var b={},c=[];a=a?a:window.location.href;a=new I(a);a=a.rc();if(a.Ya())return $e;var d="large",e=k,f;for(f in af)if(a.xa(f)){var h=a.$(f);if(!(0>h.length))switch(f){case "rsz":if("small"==h[0]||"large"==h[0])d=h[0];break;case "format":bf[h[0]]!=i&&(b.format=h[0]);break;case "ea":b.enableAds=j;break;case "client":b.enableAds=j;b.publisherId=h[0];break;
case "ned":e=h[0];break;case "topic":for(var l=[],q=0;q<h.length;q++)var t=h[q].split(","),l=l.concat(t);for(h=0;h<l.length;h++)t=l[h],q={topic:t,rsz:d},e&&(q.ned=e),c.push(q);break;case "q":l=[];for(q=0;q<h.length;q++)t=h[q].split(","),l=l.concat(t);for(h=0;h<l.length;h++)t=decodeURIComponent(l[h]),q={q:t,rsz:d},e&&(q.ned=e),c.push(q);break;case "element":"true"==h[0]&&(b.element=j)}}0==c.length&&(c=Ve);b.queryList=c;return b},Ve=[{title:Z.MSG_NEWSCAT_TOPSTORIES,topic:"h",rsz:"small"},{title:Z.MSG_NEWSCAT_BUSINESS,
topic:"b",rsz:"small"},{title:Z.MSG_NEWSCAT_SPORTS,topic:"s",rsz:"small"},{title:Z.MSG_NEWSCAT_WORLD,topic:"w",rsz:"small"},{title:Z.MSG_NEWSCAT_ENTERTAINMENT,topic:"e",rsz:"small"}],$e={queryList:Ve,format:"728x90"},af={rsz:j,ned:j,topic:j,q:j,format:j,ea:j,client:j,element:j},bf={"728x90":j,"300x250":j},Ye={p:Z.MSG_NEWSCAT_POLITICS,b:Z.MSG_NEWSCAT_BUSINESS,e:Z.MSG_NEWSCAT_ENTERTAINMENT,h:Z.MSG_NEWSCAT_TOPSTORIES,m:Z.MSG_NEWSCAT_HEALTH,n:Z.MSG_NEWSCAT_NATION,s:Z.MSG_NEWSCAT_SPORTS,t:Z.MSG_NEWSCAT_SCITECH,
w:Z.MSG_NEWSCAT_WORLD};qa("google.elements.NewsShow",X);r(X,"UrlToOptions",cf);var ef=function(a,b){var c;c=a.getFullYear();var d=a.getMonth(),e=b.MSG_MONTH_ABBR[d],f=a.getDate();10>f&&(f="0"+f);switch(b.CONST_SHORT_DATE_PATTERN){case "MDY":c=e+" "+f+", "+c;break;case "YMD":var h=b.CONST_LOCALE;"zh-CN"==h||"zh-TW"==h||"ja"==h||"ko"==h?(e=df[h],c=c+e.year+(d+1)+e.month+f+e.day):c=c+" "+e+" "+f;break;default:case "DMY":c=f+" "+e+" "+c}return c},df={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",
year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}},Ze=function(a,b){var c=new Date,c=c.getTime(),d=a.getTime();if(c<d)return b.MSG_MINUTES_AGO(2);c-=d;return 36E5>c?(c=Math.floor(c/6E4),c=1>=c?2:c,b.MSG_MINUTES_AGO(c)):864E5>c?(c=Math.floor(c/36E5),1>=c?b.MSG_ONE_HOUR_AGO:b.MSG_HOURS_AGO(c)):ef(a,b)},Xe=function(a){this.tb=a.toLowerCase();this.dh(this.tb)};Xe.prototype.o=function(a,b){this.Q.o(a,b)};
Xe.prototype.dh=function(){this.Q=k;var a=ff[this.tb];a&&(this.se=a.serviceClass,"uds"==this.se?(this.Q=new I(google.loader.GoogleApisBase+a.path),this.Q.o("key",google.loader.ApiKey),this.Q.o("v","1.0")):"afsads"==this.se&&(this.Q=new I(a.path),this.Q.o("output","js"),this.Q.o("num","0"),this.Q.o("adtest","on"),this.Q.o("client","googlepsotest-afsjs")))};
Xe.prototype.send=function(a,b){var c=new kd(this.Q.toString());"uds"!=this.se&&(window.google_afs_request_done=function(a){window.google_afs_request_done=k;b(a)});c.ac(-1);c.send(a,b)};var ff={"search/news":{path:"/services/search/news",serviceClass:"uds"},"ads/afs":{path:"http://www.google.com/search",serviceClass:"afsads"}};
google.loader.loaded({"module":"elements","version":"1.0","components":["default","slideshow","newsshow"]});
google.loader.eval.elements = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['elements']) {(function() {var scripts = google.loader.eval.scripts['elements'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.elements(scripts[i]);}})();google.loader.eval.scripts['elements'] = null;}})();